name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes
  workflow_dispatch:         # can run manually too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render backend
        run: |
          curl -s https://code-crush-backend-32ww.onrender.com/ > /dev/null